# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.quit_button = QtWidgets.QPushButton(self.centralwidget)
        self.quit_button.setGeometry(QtCore.QRect(20, 290, 75, 23))
        self.quit_button.setObjectName("quit_button")
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_button.setGeometry(QtCore.QRect(150, 410, 75, 23))
        self.open_button.setObjectName("open_button")
        self.display1 = QtWidgets.QLineEdit(self.centralwidget)
        self.display1.setGeometry(QtCore.QRect(310, 400, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.display1.setFont(font)
        self.display1.setReadOnly(True)
        self.display1.setObjectName("display1")
        self.display2 = QtWidgets.QSpinBox(self.centralwidget)
        self.display2.setGeometry(QtCore.QRect(630, 410, 42, 22))
        self.display2.setReadOnly(True)
        self.display2.setObjectName("display2")
        self.form1_button = QtWidgets.QPushButton(self.centralwidget)
        self.form1_button.setGeometry(QtCore.QRect(20, 80, 75, 23))
        self.form1_button.setObjectName("form1_button")
        self.form2_button = QtWidgets.QPushButton(self.centralwidget)
        self.form2_button.setGeometry(QtCore.QRect(20, 190, 75, 23))
        self.form2_button.setObjectName("form2_button")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(120, 20, 640, 360))
        self.widget1.setObjectName("widget1")
        self.value_1 = QtWidgets.QLineEdit(self.widget1)
        self.value_1.setGeometry(QtCore.QRect(60, 140, 113, 31))
        self.value_1.setObjectName("value_1")
        self.value_2 = QtWidgets.QLineEdit(self.widget1)
        self.value_2.setGeometry(QtCore.QRect(260, 140, 113, 31))
        self.value_2.setObjectName("value_2")
        self.value_sum = QtWidgets.QLineEdit(self.widget1)
        self.value_sum.setGeometry(QtCore.QRect(470, 139, 113, 31))
        self.value_sum.setReadOnly(True)
        self.value_sum.setObjectName("value_sum")
        self.label_1 = QtWidgets.QLabel(self.widget1)
        self.label_1.setGeometry(QtCore.QRect(190, 141, 54, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setGeometry(QtCore.QRect(400, 140, 54, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.calculate_button = QtWidgets.QPushButton(self.widget1)
        self.calculate_button.setGeometry(QtCore.QRect(240, 240, 75, 23))
        self.calculate_button.setObjectName("calculate_button")
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(120, 20, 640, 360))
        self.widget2.setObjectName("widget2")
        self.sum_display = QtWidgets.QLCDNumber(self.widget2)
        self.sum_display.setGeometry(QtCore.QRect(133, 80, 281, 131))
        font = QtGui.QFont()
        font.setFamily("Brush Script MT")
        font.setPointSize(48)
        font.setItalic(True)
        self.sum_display.setFont(font)
        self.sum_display.setObjectName("sum_display")
        self.wel_widget = QtWidgets.QWidget(self.centralwidget)
        self.wel_widget.setGeometry(QtCore.QRect(120, 20, 640, 360))
        self.wel_widget.setObjectName("wel_widget")
        self.welcome = QtWidgets.QLabel(self.wel_widget)
        self.welcome.setGeometry(QtCore.QRect(0, 0, 640, 360))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.welcome.setFont(font)
        self.welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome.setObjectName("welcome")
        self.wel_widget.raise_()
        self.widget1.raise_()
        self.widget2.raise_()
        self.quit_button.raise_()
        self.open_button.raise_()
        self.display1.raise_()
        self.display2.raise_()
        self.form1_button.raise_()
        self.form2_button.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.quit_button.setText(_translate("MainWindow", "退出"))
        self.open_button.setText(_translate("MainWindow", "弹窗"))
        self.form1_button.setText(_translate("MainWindow", "界面1"))
        self.form2_button.setText(_translate("MainWindow", "界面2"))
        self.label_1.setText(_translate("MainWindow", "+"))
        self.label_2.setText(_translate("MainWindow", "="))
        self.calculate_button.setText(_translate("MainWindow", "计算"))
        self.welcome.setText(_translate("MainWindow", "Welcome!"))

